# models.py
# Pydantic request/response models shared between FastAPI and MCP server
# These define the data contracts for every API call.

from datetime import date, datetime
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field, validator


# ─────────────────────────────────────────────────────────────
# REQUEST MODELS  (what clients send IN)
# ─────────────────────────────────────────────────────────────

class LoanCreateRequest(BaseModel):
    """
    Payload to create a new loan via POST /loans.
    All fields map 1:1 to public.retail_lending columns.
    loan_id is auto-generated by the backend — do NOT send it.
    """
    borrower_name:            str   = Field(..., min_length=1, max_length=200,
                                            description="Full legal name of the borrower")
    branch_id:                str   = Field(..., min_length=1, max_length=20,
                                            description="Branch identifier, e.g. BR-001")
    loan_amount:              float = Field(..., gt=0, le=5_000_000,
                                            description="Loan amount in CAD dollars")
    loan_type:                str   = Field(..., description="'conventional' or 'insured'")
    borrower_dti:             float = Field(..., ge=0, le=100,
                                            description="Debt-to-income ratio as a percentage (e.g. 38.5)")
    borrower_credit_score:    int   = Field(..., ge=300, le=900,
                                            description="Credit score (300–900)")
    stress_test_passed:       bool  = Field(...,
                                            description="Whether the borrower passed the OSFI stress test")
    income_docs_count:        int   = Field(..., ge=0, le=10,
                                            description="Number of independent income documents on file")
    employment_verified_date: date  = Field(...,
                                            description="Date employment was verified (YYYY-MM-DD)")
    closing_date:             date  = Field(...,
                                            description="Loan closing date (YYYY-MM-DD)")
    fair_lending_reviewed:    bool  = Field(...,
                                            description="Whether fair lending review was completed")
    aml_completed:            bool  = Field(...,
                                            description="Whether AML check was completed")
    disclosure_sent_date:     date  = Field(...,
                                            description="Date closing disclosure was sent (YYYY-MM-DD)")
    underwriter_count:        int   = Field(..., ge=1, le=5,
                                            description="Number of underwriters who reviewed this loan")
    funding_date:             date  = Field(...,
                                            description="Expected funding date (YYYY-MM-DD)")

    # Optional breach tracking fields
    breach_identified_date: Optional[date] = Field(None,
                                            description="Date a breach was identified, if any")
    escalation_date:        Optional[date] = Field(None,
                                            description="Date breach was escalated, if any")

    @validator("loan_type")
    def loan_type_must_be_valid(cls, v):
        allowed = {"conventional", "insured"}
        if v.lower().strip() not in allowed:
            raise ValueError(f"loan_type must be one of {allowed}")
        return v.lower().strip()

    class Config:
        json_schema_extra = {
            "example": {
                "borrower_name":            "Jane Smith",
                "branch_id":                "BR-001",
                "loan_amount":              450000.00,
                "loan_type":                "conventional",
                "borrower_dti":             38.5,
                "borrower_credit_score":    720,
                "stress_test_passed":       True,
                "income_docs_count":        2,
                "employment_verified_date": "2026-02-20",
                "closing_date":             "2026-02-25",
                "fair_lending_reviewed":    True,
                "aml_completed":            True,
                "disclosure_sent_date":     "2026-02-20",
                "underwriter_count":        1,
                "funding_date":             "2026-02-25",
            }
        }


# ─────────────────────────────────────────────────────────────
# RESPONSE MODELS  (what the API sends BACK)
# ─────────────────────────────────────────────────────────────

class LoanSummary(BaseModel):
    """Lightweight loan row — used in list endpoints."""
    loan_id:       str
    borrower_name: str
    branch_id:     str
    loan_amount:   float
    loan_type:     str
    funding_date:  Optional[date]

    class Config:
        from_attributes = True


class LoanWithCompliance(BaseModel):
    """Loan row joined with its latest compliance result — used in portfolio table."""
    loan_id:          str
    borrower_name:    str
    branch_id:        str
    loan_amount:      float
    loan_type:        str
    funding_date:     Optional[date]
    compliance_score: Optional[int]
    overall_status:   Optional[str]
    severity:         Optional[str]
    checked_at:       Optional[datetime]

    class Config:
        from_attributes = True


class ComplianceResult(BaseModel):
    """Full compliance result for a single loan."""
    result_id:           str
    loan_id:             str
    checked_at:          datetime
    control_results:     Dict[str, bool]
    compliance_score:    int
    overall_status:      str          # 'COMPLIANT' or 'BREACH'
    breach_explanations: Optional[str]
    severity:            str          # 'Clean', 'Low', 'Medium', 'High'

    class Config:
        from_attributes = True


class PortfolioSummary(BaseModel):
    """Aggregate compliance statistics across all loans."""
    total_loans:      int
    compliant_count:  int
    breach_count:     int
    high_severity:    int
    medium_severity:  int
    low_severity:     int


class LoanCreateResponse(BaseModel):
    """Response after successfully creating a loan."""
    loan_id:    str
    message:    str
    status:     str   # 'inserted' — CDC pipeline will pick it up automatically


class NextLoanIdResponse(BaseModel):
    """Response from GET /loans/next-id"""
    next_loan_id: str


class HealthResponse(BaseModel):
    """Response from GET /health"""
    status:   str
    service:  str
    database: str
    version:  str
